version: '3'

services:
  api:
    container_name: todo-api
    build: ./
    ports:
      - '4000:4000'
    environment:
      DATABASE_URL: 'file:./dev.db'
      JWT_SECRET: 'alksdj89102ejmdmcv0912821'
    # network_mode: host
